---

# serverless has issues if we create a bucket in CF and reference it as an event.
# so we're going to let serverless create the bucket, and only reference it in CF policy
# https://github.com/serverless/serverless/issues/2967
# https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference

#S3BucketGitmaskapi:
#  Type: AWS::S3::Bucket
#  Properties:
#    BucketName: "${self:service}-${opt:stage, self:provider.stage}-upload"


GitmaskUploadBucketPolicy:
  DependsOn: "S3BucketGitmaskapi${opt:stage, self:provider.stage}upload"
  Type: AWS::S3::BucketPolicy
  Properties:
    PolicyDocument:
      Id: Grant access readonly access to public users
      Statement:
      - Sid: PublicReadPerms
        Effect: Allow
        Principal: "*"
        Action:
        - s3:GetObject
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: "S3BucketGitmaskapi${opt:stage, self:provider.stage}upload"
            - "/*"
    Bucket:
      Ref: "S3BucketGitmaskapi${opt:stage, self:provider.stage}upload"
